/*
 * RunTimeStackAlalyzer_Config.h
 *
 *  Created on: Sep 25, 2023
 *      Author: Ali Emad
 */

#ifndef COTS_OS_INC_LIB_RUNTIMESTACKALALYZER_RUNTIMESTACKALALYZER_CONFIG_H_
#define COTS_OS_INC_LIB_RUNTIMESTACKALALYZER_RUNTIMESTACKALALYZER_CONFIG_H_

/*
 * Driver enable state.
 */
#define ucCONF_RUN_TIME_STACK_ALALYZER_ENABLE					0

/*
 * Maximum number of tasks to be analyzed.
 */
#define uiCONF_RUN_TIME_STACK_ALALYZER_MAX_NUMBER_OF_TASKS		20



#endif /* COTS_OS_INC_LIB_RUNTIMESTACKALALYZER_RUNTIMESTACKALALYZER_CONFIG_H_ */
